/**
 * Pixel art vẽ bằng ma trận ký tự: mỗi ký tự là một điểm ảnh theo bảng màu PALETTE, "." là trong suốt.
 * Thay đổi hình chỉ cần sửa chuỗi, không phải sửa code vẽ.
 */

export const PALETTE: Record<string, number> = {
  k: 0x2b1d14, // viền
  w: 0xffffff,
  W: 0xd9d9d9,
  g: 0x9e9e9e,
  r: 0xd84a3a,
  R: 0xa83226,
  y: 0xf4c542,
  Y: 0xc9962a,
  o: 0xf28c28,
  b: 0x8b5a2b,
  B: 0x5a3a22,
  c: 0xf6e3c4,
  t: 0xd9a066,
  e: 0xb5651d,
  l: 0x81d4fa,
  L: 0x3b82c4,
  n: 0x3aa35b,
  N: 0x2a7a43,
  p: 0xf06292,
  s: 0xb0bec5, // thép sáng
  S: 0x78909c, // thép tối
  i: 0xe1f5fe, // kính lạnh
};

export type Sprite = readonly string[];

/** Trả về danh sách lỗi của một sprite (kích thước, ký tự lạ). */
export function validateSprite(rows: Sprite, size = 16, height = size): string[] {
  const errors: string[] = [];
  if (rows.length !== height) errors.push(`có ${rows.length} dòng, cần ${height}`);
  rows.forEach((row, y) => {
    if (row.length !== size) errors.push(`dòng ${y} dài ${row.length}, cần ${size}`);
    for (const ch of row) if (ch !== '.' && !(ch in PALETTE)) errors.push(`dòng ${y} có ký tự lạ "${ch}"`);
  });
  return errors;
}

export const PRODUCT_SPRITES: Record<string, Sprite> = {
  mi_goi: [
    '................',
    '.kkkkkkkkkkkkkk.',
    'kRrrrrrrrrrrrrRk',
    'krrwrrrrrrrrrrrk',
    'krrrrrrrrrrrrrrk',
    'kyyyyyyyyyyyyyyk',
    'kyoyyoyyoyyoyyyk',
    'kyyoyyoyyoyyoyyk',
    'kyyyyyyyyyyyyyyk',
    'krrrrrrrrrrrrrrk',
    'krrrwwwwwwrrrrrk',
    'krrrrrrrrrrrrrrk',
    'kRrrrrrrrrrrrrRk',
    '.kkkkkkkkkkkkkk.',
    '................',
    '................',
  ],
  gao: [
    '................',
    '......kkkk......',
    '.....kBbbBk.....',
    '......kcck......',
    '....kkcccckk....',
    '...kccccccccck..',
    '..kccccccccccck.',
    '..kcrrrrrrrrrck.',
    '..kcrwwrwwrwrck.',
    '..kcrrrrrrrrrck.',
    '..kccccccccccck.',
    '..kcccWccWcccck.',
    '..kccccccccccck.',
    '...kccccccccck..',
    '....kkkkkkkk....',
    '................',
  ],
  nuoc_mam: [
    '......kkkk......',
    '......krrk......',
    '......kRRk......',
    '......kwwk......',
    '......kwwk......',
    '.....kweewk.....',
    '....kweeeewk....',
    '....keeeeeek....',
    '....kyyyyyyk....',
    '....kyrrrryk....',
    '....kyrwwryk....',
    '....kyrrrryk....',
    '....kyyyyyyk....',
    '....keeeeeek....',
    '....keeeeeek....',
    '.....kkkkkk.....',
  ],
  dau_an: [
    '.....kkkkk......',
    '.....knnnk......',
    '.....kNNNk......',
    '......kwk.......',
    '.....kwwwk......',
    '....kwyyywk.....',
    '...kwyyyyywk....',
    '...kyyyyyyyk....',
    '...knnnnnnnk....',
    '...knwwwwwnk....',
    '...knnnnnnnk....',
    '...kyyyyyyyk....',
    '...kywyyyyyk....',
    '...kyyyyyyyk....',
    '...kYYYYYYYk....',
    '....kkkkkkk.....',
  ],
  duong: [
    '................',
    '...kkkkkkkkkk...',
    '...kWwwwwwwWk...',
    '...kwwwwwwwwk...',
    '...kLLLLLLLLk...',
    '...kLwwLLwwLk...',
    '...kLLLLLLLLk...',
    '...kwwwwwwwwk...',
    '...kwWWwwWWwk...',
    '...kwWWwwWWwk...',
    '...kwwwwwwwwk...',
    '...kwwwWWwwwk...',
    '...kwwwWWwwwk...',
    '...kwwwwwwwwk...',
    '...kkkkkkkkkk...',
    '................',
  ],
  muoi: [
    '................',
    '.....kkkkkk.....',
    '....kggggggk....',
    '....kgkggkgk....',
    '....kggggggk....',
    '....kkkkkkkk....',
    '....klwwwwlk....',
    '....klwwwwlk....',
    '....klwWwwlk....',
    '....klwwwwlk....',
    '....klwwWwlk....',
    '....klwwwwlk....',
    '....klWwwwlk....',
    '....klwwwwlk....',
    '....kkkkkkkk....',
    '................',
  ],
  snack: [
    '................',
    '..kkkkkkkkkkkk..',
    '..kRRRRRRRRRRk..',
    '..kooooooooook..',
    '..kowwwwwwwwok..',
    '..kooooooooook..',
    '..koooyyyyoook..',
    '..kooyyyYyyook..',
    '..kooyyYyyyook..',
    '..koooyyyyoook..',
    '..kooooooooook..',
    '..kooooooooook..',
    '..kRRRRRRRRRRk..',
    '..kkkkkkkkkkkk..',
    '................',
    '................',
  ],
  keo: [
    '................',
    '................',
    '................',
    '................',
    'kpk...kkkk...kpk',
    'kppk.kppppk.kppk',
    'kpppkpwwpppkpppk',
    'kpppkppppppkpppk',
    'kpppkppppRpkpppk',
    'kppk.kppppk.kppk',
    'kpk...kkkk...kpk',
    '................',
    '................',
    '................',
    '................',
    '................',
  ],
  banh_quy: [
    '................',
    '................',
    '.....kkkkkk.....',
    '...kkttttttkk...',
    '..kttBtttttttk..',
    '.kttttBtttttttk.',
    '.kttttttttBtttk.',
    '.ktBttttttttttk.',
    '.kttttttBtttttk.',
    '.ktttttttttttBk.',
    '.kttBtttttttttk.',
    '..kttttttBtttk..',
    '...kkttttttkk...',
    '.....kkkkkk.....',
    '................',
    '................',
  ],
  que_cay: [
    '................',
    '...kkkkkkkkkk...',
    '...kRRRRRRRRk...',
    '...krrrrrrrrk...',
    '...krrryrrrrk...',
    '...krryyyrrrk...',
    '...kryyoyyrrk...',
    '...kryoooyyrk...',
    '...kryoooyyrk...',
    '...krryyyyrrk...',
    '...krrrrrrrrk...',
    '...krwwwwwwrk...',
    '...krrrrrrrrk...',
    '...kRRRRRRRRk...',
    '...kkkkkkkkkk...',
    '................',
  ],
  xa_phong: [
    '................',
    '..........kk....',
    '.........kwwk...',
    '..........kk....',
    '......kk........',
    '.....kwwk.......',
    '......kk........',
    '..kkkkkkkkkkkk..',
    '.klwwlllllllllk.',
    '.klwllllllllllk.',
    '.kllllLLLLllllk.',
    '.kllllllllllllk.',
    '.kLLLLLLLLLLLLk.',
    '..kkkkkkkkkkkk..',
    '................',
    '................',
  ],
  kem_danh_rang: [
    '................',
    '................',
    '................',
    '................',
    '................',
    '..kkkkkkkkkkk...',
    '.kwwwwwwwwwwwkkk',
    'kwwLLLLLLLwwwkrk',
    'kwLwwwwwwLwwwkrk',
    'kwwLLLLLLLwwwkrk',
    '.kwwwwwwwwwwwkkk',
    '..kkkkkkkkkkk...',
    '................',
    '................',
    '................',
    '................',
  ],
  giay_vs: [
    '................',
    '................',
    '....kkkkkkkk....',
    '...kWWWWWWWWk...',
    '...kWWWkkWWWk...',
    '...kwWWWWWWwk...',
    '...kwwwwwwwwk...',
    '...kwwwwwwwWk...',
    '...kwwwwwwwWk...',
    '...kwwwwwwwWk...',
    '...kwwwwwwwWk...',
    '...kwwwwwwwWk...',
    '...kwwwwwwwWk...',
    '...kwwwwwwwWk...',
    '....kkkkkkkk....',
    '................',
  ],
  pin: [
    '................',
    '......kkkk......',
    '......kYYk......',
    '....kkkkkkkk....',
    '....kyyyyyyk....',
    '....knnnnnnk....',
    '....knnwnnnk....',
    '....knwwwnnk....',
    '....knnwnnnk....',
    '....knnnnnnk....',
    '....knnnnnnk....',
    '....kNNNNNNk....',
    '....knnnnnnk....',
    '....kggggggk....',
    '....kkkkkkkk....',
    '................',
  ],
  nuoc_ngot: [
    '................',
    '.....kkkkkk.....',
    '....kWggggWk....',
    '....kkkkkkkk....',
    '....krrrrrrk....',
    '....krwrrrrk....',
    '....krwrrrrk....',
    '....kwwwwwwk....',
    '....krrrrrrk....',
    '....krrwwrrk....',
    '....krrrrrrk....',
    '....krrrrrrk....',
    '....kRrrrrRk....',
    '....kkkkkkkk....',
    '....kWggggWk....',
    '.....kkkkkk.....',
  ],
  nuoc_suoi: [
    '......kkkk......',
    '......kLLk......',
    '......kkkk......',
    '.....klllwk.....',
    '....klllllwk....',
    '....kllllllk....',
    '....kLLLLLLk....',
    '....kwwwwwwk....',
    '....kwLLLLwk....',
    '....kwwwwwwk....',
    '....kllllllk....',
    '....kllllllk....',
    '....kllllllk....',
    '....kllllllk....',
    '.....kkkkkk.....',
    '................',
  ],
  tra_xanh: [
    '......kkkk......',
    '......kwwk......',
    '......kkkk......',
    '.....knnnnk.....',
    '....knnnnnnk....',
    '....kyyyyyyk....',
    '....kyyyyyyk....',
    '....knnnnnnk....',
    '....knwwwwnk....',
    '....knwNNwnk....',
    '....knwwwwnk....',
    '....knnnnnnk....',
    '....kyyyyyyk....',
    '....kyyyyyyk....',
    '.....kkkkkk.....',
    '................',
  ],
  tang_luc: [
    '................',
    '.....kkkkkk.....',
    '....kWggggWk....',
    '....kkkkkkkk....',
    '....kLLLLLLk....',
    '....kLLLyLLk....',
    '....kLLyyLLk....',
    '....kLyyyyLk....',
    '....kLLLyyLk....',
    '....kLLLyLLk....',
    '....kLLyLLLk....',
    '....kLLLLLLk....',
    '....kLLLLLLk....',
    '....kkkkkkkk....',
    '....kWggggWk....',
    '.....kkkkkk.....',
  ],
  sua_hop: [
    '................',
    '........kk......',
    '.......kWk......',
    '...kkkkkWkkkk...',
    '...kwwwwwwwwk...',
    '...kwwwwwwwwk...',
    '...kLLLLLLLLk...',
    '...kLwwLLLLLk...',
    '...kLwwLLLLLk...',
    '...kLLLLLLLLk...',
    '...kwwwwwwwwk...',
    '...kwllwwllwk...',
    '...kwwwwwwwwk...',
    '...kwwwwwwwwk...',
    '...kkkkkkkkkk...',
    '................',
  ],
  trung_ga: [
    '................',
    '................',
    '................',
    '.....kkk........',
    '....kcccck......',
    '...kccwcccck....',
    '...kcwcccccck...',
    '..kcccccccccck..',
    '..kcccccccccck..',
    '..kccccccccctk..',
    '..kcccccccccttk.',
    '...kcccccccttk..',
    '...kcccccctttk..',
    '....kktttttkk...',
    '......kkkkk.....',
    '................',
  ],
  banh_mi: [
    '................',
    '................',
    '................',
    '..........kkk...',
    '........kktttk..',
    '......kkttttyk..',
    '....kkttytttk...',
    '...kttttttytk...',
    '..kttytttttk....',
    '..kttttytttk....',
    '.kttttttttk.....',
    '.kyttttyttk.....',
    '.kteeeeeek......',
    '..kkkkkkk.......',
    '................',
    '................',
  ],
  rau_muong: [
    '................',
    '..k....k....k...',
    '.knk..knk..knk..',
    '.knnk.knk.knnk..',
    '..knk.knk.knk...',
    '..knnkknkknnk...',
    '...knknnnknk....',
    '....knnnnnk.....',
    '....kNnnnNk.....',
    '.....kNnNk......',
    '.....kNnNk......',
    '....kyyyyyk.....',
    '....kNnnNNk.....',
    '.....kNnNk......',
    '.....kNNNk......',
    '......kkk.......',
  ],
  sua_tuoi: [
    '................',
    '......kkkk......',
    '.....kwwwwk.....',
    '.....kkkkkk.....',
    '....kwwwwwwk....',
    '...kwwwwwwwwk...',
    '...kwwwwwwwwk...',
    '...kLLLLLLLLk...',
    '...kLwLLLLwLk...',
    '...kLLwwwwLLk...',
    '...kLLLLLLLLk...',
    '...kwwwwwwwwk...',
    '...kwwwwwwwwk...',
    '...kwwwwwwwwk...',
    '....kkkkkkkk....',
    '................',
  ],
  dau_hu: [
    '................',
    '................',
    '................',
    '................',
    '....kkkkkkkk....',
    '...kccccccccck..',
    '..kcccccccccck..',
    '..kkkkkkkkkkck..',
    '..kcccccccckck..',
    '..kcccwcccckck..',
    '..kcccccccckck..',
    '..kccccccccckk..',
    '..kcccccccccck..',
    '..kkkkkkkkkkkk..',
    '................',
    '................',
  ],
  kem_que: [
    '................',
    '.....kkkkk......',
    '....kpppppk.....',
    '...kppwppppk....',
    '...kpwppppk.....',
    '...kpppppppk....',
    '...kppppppk.....',
    '...kpppppppk....',
    '...kppppppk.....',
    '....kpppppk.....',
    '.....kkkkk......',
    '.......kbk......',
    '.......kbk......',
    '.......kbk......',
    '.......kkk......',
    '................',
  ],
  kem_hop: [
    '................',
    '................',
    '...kkkkkkkkkk...',
    '..kpppppppppppk.',
    '..kkkkkkkkkkkkk.',
    '..kwwwwwwwwwwwk.',
    '..kwppwwwwLLwwk.',
    '..kwppwwwwLLwwk.',
    '..kwwwwyywwwwwk.',
    '..kwwwwyywwwwwk.',
    '..kwwwwwwwwwwwk.',
    '..kLLLLLLLLLLLk.',
    '..kLLLLLLLLLLLk.',
    '...kkkkkkkkkkk..',
    '................',
    '................',
  ],
  xuc_xich: [
    '................',
    '................',
    '................',
    '............kk..',
    '..........kkRk..',
    '........kkrrRk..',
    '......kkrrrrk...',
    '.....krrwrrk....',
    '....krrwrrk.....',
    '...krrrrrk......',
    '..krrrrRk.......',
    '..kRrrRk........',
    '..kkRkk.........',
    '...kk...........',
    '................',
    '................',
  ],
  ha_cao: [
    '................',
    '................',
    '................',
    '................',
    '......kkkk......',
    '....kkccwcck....',
    '...kcccwccwck...',
    '..kcwccccwcck...',
    '..kcccccccccck..',
    '..kcccccccccck..',
    '..kttcccccccttk.',
    '...kttttttttk...',
    '....kkkkkkkk....',
    '................',
    '................',
    '................',
  ],
  cha_gio: [
    '................',
    '................',
    '................',
    '...........kk...',
    '.........kkyYk..',
    '.......kkyyyYk..',
    '.....kkyyYyyk...',
    '....kyyyyyyk....',
    '...kyYyyyyk.....',
    '..kyyyyYyk......',
    '..kYyyyyk.......',
    '..kYYyyk........',
    '...kkkk.........',
    '................',
    '................',
    '................',
  ],
  nuoc_da: [
    '................',
    '.......kk.......',
    '......kWWk......',
    '.....kkkkkk.....',
    '....kllllllk....',
    '...kllwlllllk...',
    '...klwllwlllk...',
    '...kllllllwlk...',
    '...klwlllllllk..',
    '...kllllwlllk...',
    '...klllllllwk...',
    '...kllwllllllk..',
    '...klllllllllk..',
    '....kllllllllk..',
    '.....kkkkkkkk...',
    '................',
  ],
};

// Hàng sau quầy có sprite riêng để phân biệt rõ khi xếp ở quầy nhỏ.
PRODUCT_SPRITES.the_cao = [
  '................', '....kkkkkkkk....', '...kLLLLLLLLk...', '..kLwwwwwwwwLk..',
  '.kLwwwwwwwwwwLk.', '.kLwwwwwwwwwwLk.', '.kLwwLLLLwwwwLk.', '.kLwwLLLLwwwwLk.',
  '.kLwwwwwwwwwwLk.', '.kLwwwwwwwwwwLk.', '..kLwwwwwwwwLk..', '...kLLLLLLLLk...',
  '....kkkkkkkk....', '................', '................', '................',
];
PRODUCT_SPRITES.gas_mini = [
  '................', '.......kk.......', '......kYYk......', '......kYYk......',
  '.....kkrrkk.....', '....krrrrrrk....', '...krrrrrrrrk...', '...krrwwrrrrk...',
  '...krrrrrrrrk...', '...krrrrrrrrk...', '...krrrrrrrrk...', '...krrrrrrrrk...',
  '....krrrrrrk....', '.....kkkkkk.....', '................', '................',
];
PRODUCT_SPRITES.bat_lua = [
  '................', '..........kYY...', '.........kYyYk..', '..........kYY...',
  '......kkkkkk....', '.....kYYYYYYk...', '.....kYwwwwwYk..', '.....kYwyywYk...',
  '.....kYwwwwwYk..', '.....kYYYYYYk...', '.....kNNNNNNk...', '.....kNnnnnNk...',
  '.....kNnnnnNk...', '......kkkkkk....', '................', '................',
];

/** Nội thất nhìn chính diện; kích thước khớp footprint (1 ô = 16 điểm ảnh). */
export const FURNITURE_SPRITES: Record<string, Sprite> = {
  shelf: [
    'kkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkk',
    'kttttttttttttttttttttttttttttttk',
    'keccccccccccccccccccccccccccccek',
    'keckrckyckncklckpckockLckyckrcek',
    'kecrrcyycnncllcppcoocLLcyycrrcek',
    'kecrrcyycnncllcppcoocLLcyycrrcek',
    'kecrrcyycnncllcppcoocLLcyycrrcek',
    'kBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBk',
    'keccccccccccccccccccccccccccccek',
    'kecwwcwwcwwcwwcwwcwwcwwcwwcwwcek',
    'kecrrcyycLLcoocppcllcnncyycrrcek',
    'kecrrcyycLLcoocppcllcnncyycrrcek',
    'kecrrcyycLLcoocppcllcnncyycrrcek',
    'kBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBk',
    'kkkeeeeeeeeeeeeeeeeeeeeeeeeeekkk',
    'kkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkk',
  ],
  fridge: [
    'kkkkkkkkkkkkkkkk',
    'kLLLLLLLLLLLLLLk',
    'kLLwLLwLLwLLwLLk',
    'kLLLLLLLLLLLLLLk',
    'kWWWWWWWWWWWWWWk',
    'kWSSSSSSSSSSSSWk',
    'kWSwwiiiiiiiiSWk',
    'kWSwwriwniwyiSWk',
    'kWSirrinniyyiSWk',
    'kWSirrinniyyiSWk',
    'kWSirrinniyyiSWk',
    'kWSssssssssssSWk',
    'kWSiiiiiiiiiiSWk',
    'kWSiwoiwliwpkSWk',
    'kWSiooillippkSWk',
    'kWSiooillippkSWk',
    'kWSiooillippkSWk',
    'kWSssssssssskSWk',
    'kWSiiiiiiiiikSWk',
    'kWSiwriwLiwniSWk',
    'kWSirriLLinniSWk',
    'kWSirriLLinniSWk',
    'kWSirriLLinniSWk',
    'kWSssssssssssSWk',
    'kWSiiiiiiiiiiSWk',
    'kWSllllllllllSWk',
    'kWSllllllllllSWk',
    'kWSSSSSSSSSSSSWk',
    'kWWWWWWWWWWWWWWk',
    'kggggggggggggggk',
    'kggggggggggggggk',
    'kkkkkkkkkkkkkkkk',
  ],
  freezer: [
    '.SSSSSSSSSSSSSSSSSSSSSSSSSSSSSS.',
    '.SiwiiiiwiiiiwiiiiwiiiiwiiiiwiS.',
    '.SippiyyillioowppirriwwinniiiwS.',
    'kSippiyyilliooippirriwwinniiiiSk',
    'kSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSk',
    'kwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwk',
    'kwLLLLLLLLLLLLLLLLLLLLLLLLLLLLwk',
    'kwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwk',
    'kwwllllllllllllllllllllllllllwwk',
    'kwwllllllllllwwwwwwllllllllllwwk',
    'kwwllllllllllwLLLLwllllllllllwwk',
    'kwwllllllllllwwwwwwllllllllllwwk',
    'kwwllllllllllllllllllllllllllwwk',
    'kwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwk',
    'kggggggggggggggggggggggggggggggk',
    'kkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkk',
  ],
  storage_rack: [
    '.S............S.',
    '.Sbbyybb......S.',
    '.SbttttbbbbbbbS.',
    '.SbttttbbccccbS.',
    '.SbbbbbbbbbbbbS.',
    '.ssssssssssssss.',
    '.SbbbbbbbyyybbS.',
    '.SbcccbbtttttbS.',
    '.SbcccbbtttttbS.',
    '.SbbbbbbbbbbbbS.',
    '.ssssssssssssss.',
    '.S.bbbyyyybbb.S.',
    '.S.bttttttttb.S.',
    '.S.bttttttttb.S.',
    '.S.bbbbbbbbbb.S.',
    '.ssssssssssssss.',
  ],
  counter: [
    '..................kkkkkkkkkkk...',
    '..................knnnnnnnnnk...',
    '..................knnnnnnnnnk...',
    '....yyy...........kgggggggggk...',
    '...yyyyy..........kgwgwgwgwgk...',
    '...yyyyy..........kkkkkkkkkkk...',
    'kttttttttttttttttttttttttttttttk',
    'kttttttttttttttttttttttttttttttk',
    'kbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbk',
    'kbbbBbbbbbBbbbbbBbbbbbBbbbbbBbbk',
    'kbbbBbbbbbBbbbbbBbbbbbBbbbbbBbbk',
    'kbbbBbbbbbBbbbbbBbbbbbBbbbbbBbbk',
    'kbbbBbbbbbBbbbbbBbbbbbBbbbbbBbbk',
    'kbbbBbbbbbBbbbbbBbbbbbBbbbbbBbbk',
    'kbbbBbbbbbBbbbbbBbbbbbBbbbbbBbbk',
    'kkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkk',
  ],
  chau_cay: [
    '................',
    '.......n........',
    '......n.n.......',
    '....nnnnNnn.....',
    '.....nNnnnn.....',
    '...nnnnnnnnnn...',
    '...nnnnnnNnnn...',
    '...nnNnnnnnnn...',
    '.....nnNNnn.....',
    '.......NN.......',
    '...oooooooooo...',
    '....keeeeeek....',
    '....keeeeeek....',
    '....keeeeeek....',
    '....kkkkkkkk....',
    '................',
  ],
  shelf_steel: [
    '.ssssssssssssss.',
    '.S............S.',
    '.S.rr.yy.ll.nnS.',
    '.S.rr.yy.ll.nnS.',
    '.S.rr.yy.ll.nnS.',
    '.ssssssssssssss.',
    '.S............S.',
    '.S.ooo.ppp.LLLS.',
    '.S.ooo.ppp.LLLS.',
    '.S.ooo.ppp.LLLS.',
    '.ssssssssssssss.',
    '.S.bbbbbbbbbb.S.',
    '.S.bttttttttb.S.',
    '.S.bttttttttb.S.',
    '.S.bbbbbbbbbb.S.',
    '.ssssssssssssss.',
  ],
};
